### ISSUE TITLE
`devtools` should be assumed to be part of the static permissions if `devtools_page` is specified in the manifest

### ISSUE THREAD

**Issue by fregante** [fregante/webext-additional-permissions#6]
https://github.com/pixiebrix/pixiebrix-extension/pull/843#pullrequestreview-709011054

**Comment by twschiller** [comment]
I think this is correct. Note that "devtools" is not a permission name in the manifest though, at least in the MDN documentation: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions

**Comment by fregante** [comment]
https://developer.chrome.com/docs/extensions/reference/permissions/

You can assume MDN docs are incorrect/incomplete most of the time when compared to chrome’s docs. Occasionally I have to look into the browser source to find the answer 😅 

And found the manifest permission getter that silently adds the permission as if it was specified in the manifest:

https://github.com/mozilla/gecko-dev/blob/c0fc8c4852e927b0ae75d893d35772b8c60ee06b/toolkit/components/extensions/Extension.jsm#L729-L743

**Comment by fregante** [comment]
It turns out `devtools` cannot indeed be specified **anywhere** in the manifest or else Chrome refuses to load it. 

Even if Firefox’ code suggests that it can be specified in `optional_permissions`, Chrome refuses that too. 🤷‍♂️
